---
- name: Ensure mcelog is installed
  yum:
    name: mcelog
    state: installed
  when: "ansible_facts['os_family'] == 'RedHat'"

- name: Ensure mcelog is enabled and started
  systemd:
    state: started
    name: rsyslog
    enabled: true
    daemon-reload: yes